config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  post 'message', to: 'messages#create'
  get 'users', to: 'sessions#show'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :user
  scope :custom_display, -> { order(:created_at).last(30) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 3, maximum: 15}, uniqueness: { case_sensitiv: true }
  validates :email, presence: true, length: { minimum: 3 }, uniqueness: { case_sensitiv: true }
  validates :password, presence: true

  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to take that action"
      redirect_to login_path
    end
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params) # the the message from the params to the current user (build the connection between the user and the message ressource)
    if message.save
      ActionCable.server.broadcast 'chatroom_channel',
                                    modified_message: message_render(message) # what you send here will be received by the coffee file "received data"
    end
  end

  private

  def message_params
    params.require(:message).permit(:message)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message }) # render a partial _message.html.erb from the controller
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new # login form and submit data
    @messages = Message.all
    @users = User.all
  end

  def show # show users messages and details
    @user = current_user
    @user_messages = current_user.messages
  end

  def create # handle new form login data
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to root_path
    else
      flash.now[:error] = "Credentials were wrong."
      render 'new'
    end
  end

  def destroy # logout - delete session
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new # signup form and submit data
    @user = User.new
  end

  def create # handle new form signup data
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "#{@user.username}, you have successfully signed up"
      redirect_to root_path
    else
      flash[:error] = 'Something was wrong with your data'
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded mt-1 shadow mx-auto d-block")
  end

end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned large icon header more-space">
  <i class="circular inverted red sun outline icon"></i>
  ChatMe Say something nice
</h2>

<div class="ui two column grid">

  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
        <div class="content" id="messages">
          <div class="ui feed" id="message-container">
            <%= render @messages %>
          </div> <!-- end ui feed -->
        </div> <!-- end 12 wide column -->

      <div class="extra content">
        <%= form_for(@message, html: { class: 'ui reply form', role: 'form' }, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :message, placeholder: 'Enter a message . . .' %>
              <%= f.button '<i class="bordered red inverted icon edit"> </i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <%= link_to 'Messages', users_path, class: 'item' %>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div> <!-- end 4 column grid-->


</div> <!-- two column grid-->

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message_content| %>

  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>

<% end %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Chatroom', root_path, class: 'item' %>
<%= link_to 'Messages', users_path, class: 'item' %>

<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
        <%= link_to 'Log out', logout_path, method: :delete, class: 'item' %>
      <% else %>
        <%= link_to 'Log in', login_path, class: 'item' %>
      <% end %>
    </div>
  </div>
  <% if !logged_in? %>
    <div class="item">
      <%= link_to "Log in", login_path, class: "ui primary button font-color-highlight" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatme</title>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="ui large inverted menu">
    <div class="ui container">
      <%= render 'layouts/navbar' %>
    </div>
  </div>

  <div class="ui container">
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="label">
    <%= gravatar_for(message.user) %>
  </div>
  <div class="content">
    <div class="summary">
      <em> <%= message.user.username %> </em>: <%= message.message %>
      <div class="date">
        <%= time_ago_in_words(message.created_at) %> ago
      </div>
    </div>
  </div>
</div><!-- end event -->

app/views/users/new.html.erb
<h1 class="ui center aligned header more-space"> Welcome to ChatMe now a complete messaging app</h1>
<h2 class="ui center aligned large icon header">
  <i class="circular inverted red signup icon"></i>
  Sign up
</h2>

<div class="ui placeholder segment">
  <div class="ui one column very relaxed stackable grid">
    <div class="column">
      <%= form_for(:user, html: { class: "ui form", role: "form" }, url: signup_path) do |f| %>
        <div class="field">
          <%= f.label :username, "Username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username" %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :email, "Email" %>
          <div class="ui left icon input">
            <%= f.text_field :email, placeholder: "Email" %>
            <i class="mail icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password, "Password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Password" %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.button "Sign up", class: "ui red submit button" %>
        <% end %>
      </div>
  </div>
</div>